### ISSUE TITLE
Warning when using on empty maps

### ISSUE THREAD

**Issue by pentzzsolt** [pentzzsolt/sass-recursive-map-merge#1]
If at least one of the maps given to the function as an argument is empty, the function returns `null` and throws the warning:
>`recursive-map-merge() expects it's parameters to be map types!`

This is because Sass sees empty maps as lists:
```scss
$empty-map: ();
if type-of($empty-map) == map {
	//This code is not executed.
}
if type-of($empty-map) == list {
	//This code is executed.
}
```
Because the function checks if both arguments are maps, it fails with empty maps.
